{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8637952c",
   "metadata": {},
   "outputs": [],
   "source": [
    "# -------------------------------\n",
    "# run: streamlit run app.py\n",
    "# -------------------------------\n",
    "\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import yfinance as yf\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.ticker as mtick\n",
    "import seaborn as sns\n",
    "from sklearn.decomposition import PCA\n",
    "from sklearn.linear_model import LinearRegression\n",
    "\n",
    "st.set_page_config(page_title=\"Live Portfolio Risk Dashboard\", layout=\"wide\")\n",
    "\n",
    "# -------------------------------\n",
    "# UI STYLE\n",
    "# -------------------------------\n",
    "st.markdown(\"\"\"\n",
    "<style>\n",
    "html, body, [class*=\"css\"]  { font-size: 13px; }\n",
    "[data-testid=\"stMetric\"] {\n",
    "    background-color: #F5F7FA !important;\n",
    "    padding: 10px;\n",
    "    border-radius: 8px;\n",
    "    border: 1px solid #D0D7DE;\n",
    "}\n",
    "[data-testid=\"stMetric\"] * { color: #000000 !important; }\n",
    "</style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# -------------------------------\n",
    "# TITLE\n",
    "# -------------------------------\n",
    "st.title(\"📈 Live Portfolio Risk & Optimization Dashboard\")\n",
    "st.caption(\"Real Market Data | Risk | Optimization | ML\")\n",
    "st.markdown(\"**Created by Steven Amet**\")\n",
    "\n",
    "# -------------------------------\n",
    "# INPUT\n",
    "# -------------------------------\n",
    "st.markdown(\"### 📊 Portfolio Input\")\n",
    "\n",
    "tickers = st.text_input(\"Enter tickers (comma separated)\", \"AAPL,MSFT,GOOGL,AMZN\")\n",
    "ticker_list = [t.strip().upper() for t in tickers.split(\",\")]\n",
    "\n",
    "start_date = st.date_input(\"Start Date\", pd.to_datetime(\"2020-01-01\"))\n",
    "\n",
    "# -------------------------------\n",
    "# DATA\n",
    "# -------------------------------\n",
    "data = yf.download(ticker_list, start=start_date)[\"Adj Close\"]\n",
    "\n",
    "if data.empty:\n",
    "    st.error(\"No data found. Check tickers.\")\n",
    "    st.stop()\n",
    "\n",
    "returns = data.pct_change().dropna()\n",
    "\n",
    "# -------------------------------\n",
    "# PRICE CHART\n",
    "# -------------------------------\n",
    "st.markdown(\"### 📈 Price Chart\")\n",
    "st.line_chart(data)\n",
    "\n",
    "# -------------------------------\n",
    "# WEIGHTS\n",
    "# -------------------------------\n",
    "st.sidebar.markdown(\"### ⚖️ Portfolio Weights\")\n",
    "\n",
    "weights = []\n",
    "for t in ticker_list:\n",
    "    w = st.sidebar.slider(f\"{t}\", 0.0, 1.0, 1.0/len(ticker_list))\n",
    "    weights.append(w)\n",
    "\n",
    "weights = np.array(weights)\n",
    "weights = weights / weights.sum()\n",
    "\n",
    "# -------------------------------\n",
    "# PORTFOLIO RETURNS\n",
    "# -------------------------------\n",
    "portfolio_returns = returns.dot(weights)\n",
    "\n",
    "# -------------------------------\n",
    "# RISK METRICS\n",
    "# -------------------------------\n",
    "VaR_95 = np.percentile(portfolio_returns, 5)\n",
    "VaR_99 = np.percentile(portfolio_returns, 1)\n",
    "ES = portfolio_returns[portfolio_returns <= VaR_95].mean()\n",
    "\n",
    "mean_returns = returns.mean()\n",
    "cov = returns.cov()\n",
    "\n",
    "ret = np.dot(weights, mean_returns)\n",
    "risk = np.sqrt(weights.T @ cov @ weights)\n",
    "sharpe = ret / risk\n",
    "\n",
    "# -------------------------------\n",
    "# METRICS DISPLAY\n",
    "# -------------------------------\n",
    "st.markdown(\"### 📌 Key Risk Metrics\")\n",
    "\n",
    "st.info(\"\"\"\n",
    "- VaR = worst expected loss  \n",
    "- ES = average extreme loss  \n",
    "- Sharpe = return per unit of risk  \n",
    "\"\"\")\n",
    "\n",
    "c1, c2, c3, c4 = st.columns(4)\n",
    "c1.metric(\"VaR 99%\", f\"{VaR_99:.2%}\")\n",
    "c2.metric(\"Expected Shortfall\", f\"{ES:.2%}\")\n",
    "c3.metric(\"Return\", f\"{ret:.2%}\")\n",
    "c4.metric(\"Sharpe\", f\"{sharpe:.2f}\")\n",
    "\n",
    "# -------------------------------\n",
    "# LOSS DISTRIBUTION\n",
    "# -------------------------------\n",
    "st.markdown(\"### 📉 Loss Distribution\")\n",
    "\n",
    "st.info(\"\"\"\n",
    "- Left tail = worst losses  \n",
    "- Wider = more volatility  \n",
    "\"\"\")\n",
    "\n",
    "fig, ax = plt.subplots()\n",
    "sns.histplot(portfolio_returns, bins=40, kde=True, ax=ax, color=\"#4C72B0\")\n",
    "ax.axvline(VaR_95, linestyle=\"--\", color=\"orange\")\n",
    "ax.axvline(VaR_99, linestyle=\"--\", color=\"red\")\n",
    "plt.tight_layout()\n",
    "st.pyplot(fig)\n",
    "\n",
    "# -------------------------------\n",
    "# CORRELATION\n",
    "# -------------------------------\n",
    "st.markdown(\"### 🔗 Correlation Matrix\")\n",
    "\n",
    "st.info(\"\"\"\n",
    "- High correlation = higher systemic risk  \n",
    "- Low correlation = diversification  \n",
    "\"\"\")\n",
    "\n",
    "fig_corr, ax = plt.subplots()\n",
    "sns.heatmap(returns.corr(), annot=True, cmap=\"coolwarm\", ax=ax)\n",
    "plt.tight_layout()\n",
    "st.pyplot(fig_corr)\n",
    "\n",
    "# -------------------------------\n",
    "# PCA\n",
    "# -------------------------------\n",
    "st.markdown(\"### 📊 PCA Risk Drivers\")\n",
    "\n",
    "st.info(\"\"\"\n",
    "- First component = main risk driver  \n",
    "- Concentration = systemic risk  \n",
    "\"\"\")\n",
    "\n",
    "pca = PCA().fit(returns)\n",
    "\n",
    "fig_pca, ax = plt.subplots()\n",
    "ax.bar(range(len(pca.explained_variance_ratio_)), pca.explained_variance_ratio_, color=\"#55A868\")\n",
    "ax.yaxis.set_major_formatter(mtick.PercentFormatter(1))\n",
    "plt.tight_layout()\n",
    "st.pyplot(fig_pca)\n",
    "\n",
    "# PCA loadings\n",
    "loadings = pd.DataFrame(\n",
    "    pca.components_,\n",
    "    columns=returns.columns,\n",
    "    index=[f\"PC{i+1}\" for i in range(len(returns.columns))]\n",
    ")\n",
    "st.dataframe(loadings)\n",
    "\n",
    "# -------------------------------\n",
    "# OPTIMIZATION\n",
    "# -------------------------------\n",
    "st.markdown(\"### ⚙️ Portfolio Optimization\")\n",
    "\n",
    "st.info(\"\"\"\n",
    "Balances return vs risk.\n",
    "\"\"\")\n",
    "\n",
    "st.write(f\"Return: {ret:.2%}\")\n",
    "st.write(f\"Risk: {risk:.2%}\")\n",
    "\n",
    "# -------------------------------\n",
    "# ML MODEL\n",
    "# -------------------------------\n",
    "st.markdown(\"### 🤖 ML Prediction\")\n",
    "\n",
    "X = returns\n",
    "y = returns.sum(axis=1)\n",
    "\n",
    "model = LinearRegression().fit(X, y)\n",
    "pred = model.predict(X)\n",
    "\n",
    "fig_ml, ax = plt.subplots()\n",
    "ax.scatter(y, pred, alpha=0.6)\n",
    "ax.plot([y.min(), y.max()], [y.min(), y.max()], linestyle=\"--\", color=\"red\")\n",
    "plt.tight_layout()\n",
    "st.pyplot(fig_ml)\n",
    "\n",
    "# -------------------------------\n",
    "# EXECUTIVE SUMMARY\n",
    "# -------------------------------\n",
    "st.markdown(\"### 🧠 Executive Summary\")\n",
    "\n",
    "st.write(f\"\"\"\n",
    "This portfolio has a Value-at-Risk of {abs(VaR_99):.2%}, indicating downside exposure in extreme market conditions.\n",
    "\n",
    "The expected return is {ret:.2%} with a risk level of {risk:.2%}, resulting in a Sharpe ratio of {sharpe:.2f}.\n",
    "\n",
    "👉 Risk is primarily driven by correlations and dominant market factors.\n",
    "\"\"\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
